export const UPDATE_READY_STATE = 'UPDATE_READY_STATE';

export const UPDATE_LOADING_STATE = 'UPDATE_LOADING_STATE';

export const RESET_SNACKBAR_MSG = 'RESET_SNACKBAR_MSG';

export const SHOW_SUCCESS_MSG = 'SHOW_SUCCESS_MSG';

export const SHOW_ERROR_MSG = 'SHOW_ERROR_MSG';

export const SHOW_WARNING_MSG = 'SHOW_WARNING_MSG';